version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "biblioteca"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
